# ML Technical Analysis System Configuration
app:
  name: "ML Technical Analysis System"
  version: "2.0.0"
  environment: "development"
  seed: 42
  debug: true

# Data Configuration
data:
  symbols:
    - "BTCUSDT"
    - "ETHUSDT"
    - "SOLUSDT"
    - "ADAUSDT"
  intervals:
    - "1m"
    - "5m"
    - "15m"
    - "1h"
    - "4h"
    - "1d"
  horizons: [1, 3, 5, 10]
  start_date: "2023-01-01"
  end_date: "2024-12-31"
  max_records_per_fetch: 1000
  data_retention_days: 365

# Binance API Configuration
binance:
  base_url: "https://api.binance.com"
  klines_endpoint: "/api/v3/klines"
  limit: 1000
  request_delay_ms: 200
  max_retries: 5
  backoff_factor: 2
  timeout_seconds: 30
  rate_limit_requests_per_minute: 1200

# Path Configuration
paths:
  data: "./data"
  models: "./models"
  logs: "./logs"
  artefacts: "./artefacts"
  cache: "./cache"

# Database Configuration
database:
  url: "sqlite:///ml_ta.db"
  echo: false
  pool_size: 10
  max_overflow: 20

# Redis Configuration
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: null
  socket_timeout: 5

# Technical Indicators Configuration
indicators:
  trend:
    sma_periods: [5, 10, 20, 50, 100, 200]
    ema_periods: [5, 10, 20, 50, 100, 200]
    macd:
      fast_period: 12
      slow_period: 26
      signal_period: 9
    adx_period: 14
    parabolic_sar:
      acceleration: 0.02
      maximum: 0.2
  momentum:
    rsi_period: 14
    stochastic:
      k_period: 14
      d_period: 3
      smooth_k: 3
    williams_r_period: 14
    roc_period: 10
  volatility:
    bollinger_bands:
      period: 20
      std_dev: 2
    atr_period: 14
    keltner_channels:
      period: 20
      multiplier: 2
  volume:
    obv_enabled: true
    mfi_period: 14
    cmf_period: 20
    vwap_enabled: true

# Model Configuration
model:
  cv_folds: 5
  cv_test_size: 0.2
  cv_strategy: "expanding"
  cv_gap_size: 1
  task_type: "classification"
  hyperopt_trials: 100
  early_stopping_rounds: 50
  max_model_size_mb: 100
  model_retention_count: 10
  algorithms:
    - "lightgbm"
    - "xgboost"
    - "catboost"
    - "random_forest"

# Security Configuration
security:
  api_key_header: "X-API-Key"
  rate_limit_per_minute: 60
  max_request_size_mb: 10
  allowed_origins:
    - "http://localhost:3000"
  jwt_secret_key: "your-secret-key-here"
  jwt_algorithm: "HS256"
  jwt_expiration_hours: 24

# Monitoring Configuration
monitoring:
  metrics_port: 8000
  health_check_interval: 30
  log_level: "INFO"
  enable_profiling: false
  alert_thresholds:
    cpu_percent: 80
    memory_percent: 85
    disk_percent: 90
    prediction_latency_ms: 100
    error_rate_percent: 5
    model_accuracy_threshold: 0.6

# Performance Configuration
performance:
  max_memory_gb: 4
  max_cpu_percent: 80
  batch_size: 1000
  parallel_jobs: -1
  cache_size_mb: 512
  prediction_timeout_seconds: 10

# Feature Engineering Configuration
features:
  max_features: 200
  feature_selection_methods:
    - "mutual_info"
    - "chi2"
    - "f_classif"
  correlation_threshold: 0.95
  variance_threshold: 0.01
  rolling_windows: [5, 10, 20, 50]
  lag_periods: [1, 2, 3, 5, 10]

# Backtesting Configuration
backtest:
  initial_capital: 10000
  commission_rate: 0.001
  slippage_rate: 0.0005
  position_size_method: "fixed_fractional"
  risk_per_trade: 0.02
  max_positions: 5
